// Variaciones de frases para simular tráfico orgánico
// Podés ampliarlo cuando quieras sin tocar index.html.
window.frases = [
  "Buenas, me gustaria crear una cuenta, mi nombre es:",
  "Hola, quiero crearme un usuario, me llamo:",
  "Holaa, quiero registrarme con un usuario, soy:",
  "Hola, ¿cómo estás? quiero crear cuenta, mi nombre es:",
  "Buenas, quisiera crear un usuario, soy:",
  "Buenas tardes, me gustaria crear un usuario, me llamo:",
  "Hola! quiero hacerme una cuenta, mi nombre es:",
  "Buen día, quiero crear un usuario, soy:",
  "Hola buenas, quiero crearme un usuario, soy:",
  "Hola, me gustaría registrarme, mi nombre es:",
  "Holaa, quiero empezar creando un usuario, soy:",
  "Hola! necesito crear una cuenta, me llamo:",
  "Buenas, me interesa crear usuario, mi nombre es:",
  "Hola, quiero una cuenta nueva, me llamo:",
  "Hola, quiero crear mi cuenta, soy:",
  "Buenas noches, quiero crear un usuario, soy:",
  "Hola buenas, quisiera una cuenta, mi nombre es:",
  "Holaa! quiero crear usuario, me llamo:",
  "Buenas, quiero hacerme un usuario, soy:",
  "Hola, quiero registrarme con una cuenta, me llamo:",
  "Buenas, quiero crearme una cuenta, soy:",
  "Hola buenas, me gustaria un usuario, soy:",
  "Hola, me quiero crear un usuario, soy:",
  "Holaa, me interesa una cuenta, soy:",
  "Hola, quiero crear un usuario ahora, mi nombre es:",
  "Buenas, me gustaría tener usuario, soy:",
  "Hola, quiero crear cuenta nueva, me llamo:",
  "Buenas! quiero crear usuario ya, soy:",
  "Hola, quiero hacerme una cuenta nueva, soy:",
  "Hola buenas, quiero empezar con usuario, mi nombre es:",
  "Holaa, necesito crear cuenta, soy:",
  "Buenas, quiero registrarme, me llamo:",
  "Hola! quiero cuenta, mi nombre es:",
  "Buenas tardes, quiero crearme usuario, soy:",
  "Hola, me interesa hacer usuario, soy:",
  "Holaa, quiero una cuenta nueva, soy:",
  "Hola buenas! quiero registrarme, soy:",
  "Buenas, quiero usuario, soy:",
  "Hola, quisiera una cuenta, mi nombre es:",
  "Hola, me gustaría crear usuario, soy:",
  "Holaa! quiero crear una cuenta, soy:",
  "Buenas noches, quiero usuario, soy:",
  "Hola buenas, me quiero registrar, soy:",
  "Buenas, quiero crear mi usuario, soy:",
  "Hola, quiero abrir una cuenta, soy:",
  "Holaa, quiero registrarme con ustedes, soy:",
  "Hola buenas, quiero empezar con cuenta, soy:",
  "Buenas, me interesa crearme usuario, soy:",
  "Hola! me gustaría usuario, soy:",
  "Holaa, quiero crear usuario ya, soy:",
  "Hola buenas, quiero una cuenta nueva, soy:",
  "Buenas, quiero hacer usuario nuevo, soy:",
  "Hola, necesito cuenta, mi nombre es:",
  "Holaa! quiero usuario nuevo, soy:",
  "Buenas tardes, quiero una cuenta, soy:",
  "Hola buenas! quiero hacerme usuario, soy:",
  "Buenas, quiero crear cuenta ya, soy:",
  "Hola, quiero crear mi usuario ahora, soy:",
  "Holaa, quiero cuenta nueva ya, soy:",
  "Hola, me gustaría registrarme ahora, soy:",
  "Buenas, quiero usuario nuevo, soy:",
  "Hola buenas, quiero una cuenta ya, soy:",
  "Hola! quiero crear usuario, soy:",
  "Holaa, necesito usuario, soy:",
  "Buenas noches, me gustaría una cuenta, soy:",
  "Hola buenas, quiero usuario ya, soy:",
  "Buenas, me gustaría registrarme ahora, soy:",
  "Hola, quiero cuenta, soy:",
  "Holaa, quiero abrir usuario, soy:",
  "Hola, quiero una cuenta ya, mi nombre es:",
  "Buenas, me interesa registrarme ya, soy:",
  "Hola buenas, quiero empezar con usuario nuevo, soy:",
  "Hola! me quiero crear una cuenta, soy:",
  "Holaa, quiero registrarme ya, soy:",
  "Buenas tardes, quiero usuario nuevo ya, soy:",
  "Hola, quiero usuario nuevo, soy:",
  "Buenas, me quiero registrar con una cuenta, soy:",
  "Hola buenas, necesito usuario, soy:",
  "Holaa, quiero cuenta ya mismo, soy:",
  "Hola, me gustaría un usuario, soy:",
  "Buenas, quiero crear cuenta nueva, soy:",
  "Hola buenas, quiero registrarme cuanto antes, soy:",
  "Hola! quiero un usuario, mi nombre es:",
  "Holaa, quiero crear cuenta enseguida, soy:",
  "Buenas, me gustaría tener cuenta, soy:",
  "Hola, quiero cuenta nueva ahora, soy:",
  "Hola buenas, quiero crear mi cuenta, soy:",
  "Holaa! me interesa usuario, soy:",
  "Buenas, quiero hacerme cuenta, soy:",
  "Hola, quiero usuario ya mismo, soy:",
  "Buenas tardes, quiero cuenta, soy:",
  "Hola buenas, quiero usuario cuanto antes, soy:",
  "Holaa, quiero hacer cuenta, soy:",
  "Hola, me gustaría usuario ya, soy:",
  "Buenas, quiero registrarme en cuenta, soy:",
  "Hola buenas, me interesa usuario, soy:",
  "Hola! quiero hacer cuenta nueva, soy:",
  "Holaa, quiero registrarme como usuario, soy:"
];
